#ifndef GENERATED_ASN1SCC_Context_delay_H
#define GENERATED_ASN1SCC_Context_delay_H
/*
Code automatically generated by asn1scc tool
*/
#include "dataview-uniq.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- asn1SccContext_delay --------------------------------------------*/

typedef struct {
    asn1SccT_UInt16 nodelayedvalues;

} asn1SccContext_delay;

flag asn1SccContext_delay_Equal(const asn1SccContext_delay* pVal1, const asn1SccContext_delay* pVal2);

void asn1SccContext_delay_Initialize(asn1SccContext_delay* pVal);

#define ERR_CONTEXT_DELAY_NODELAYEDVALUES		1  /**/
flag asn1SccContext_delay_IsConstraintValid(const asn1SccContext_delay* pVal, int* pErrCode);

extern const asn1SccContext_delay delay_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif