/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Context-gr740-stream-aligner.h"


const asn1SccContext_gr740_stream_aligner gr740_stream_aligner_ctxt = {
    .perioda = 1.00000000000000000000E+000,
    .periodb = 3.00000000000000000000E+000
};


flag asn1SccContext_gr740_stream_aligner_Equal(const asn1SccContext_gr740_stream_aligner* pVal1, const asn1SccContext_gr740_stream_aligner* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->perioda == pVal2->perioda);

    if (ret) {
        ret = (pVal1->periodb == pVal2->periodb);

    }
	return ret;

}

void asn1SccContext_gr740_stream_aligner_Initialize(asn1SccContext_gr740_stream_aligner* pVal)
{


	/*set perioda */
	asn1SccT_Double_Initialize((&(pVal->perioda)));
	/*set periodb */
	asn1SccT_Double_Initialize((&(pVal->periodb)));
}

flag asn1SccContext_gr740_stream_aligner_IsConstraintValid(const asn1SccContext_gr740_stream_aligner *pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((-1.79769313486231570000E+308 <= pVal->perioda) && (pVal->perioda <= 1.79769313486231570000E+308));
    *pErrCode = ret ? 0 :  ERR_CONTEXT_GR740_STREAM_ALIGNER_PERIODA;
    if (ret) {
        ret = ((-1.79769313486231570000E+308 <= pVal->periodb) && (pVal->periodb <= 1.79769313486231570000E+308));
        *pErrCode = ret ? 0 :  ERR_CONTEXT_GR740_STREAM_ALIGNER_PERIODB;
    }

	return ret;
}

